SyntaxError Fix
Initially, if you try to run `npm test` on a recently generated project, the following error appear:
```
SyntaxError: .../src/components/Counter.js: A semicolon is required after a class property (11:3)
   9   |     decrement: PropTypes.func.isRequired,
  10  |     counter: PropTypes.number.isRequired
> 11 |   }
        |    ^
```

Adding the semicolon solves the problem.